version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/admin/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/admin/docker/caddy/site:/srv
      - /home/admin/docker/caddy/caddy_data:/data
      - /home/admin/docker/caddy/caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
